### ISSUE TITLE
Leading with U+ rather than 0x

### ISSUE THREAD

**Issue by netjeff** [EmNudge/unicode-lookup#5]
I just discovered this tool, love it!

For codepoints shown in hex, the convention is usually to lead with **U+** rather than **0x**, so U+1a2f rather than 0x1a2f.   For example see the FAQs at unicode.org, like https://www.unicode.org/faq/punctuation_symbols.html

Maybe update the display to show as U+1a2f, and allow simple search on both U+1a2f and 0x1a2f?

**Comment by EmNudge** [comment]
Good point! Not sure why I didn't see this issue until just now.

I've moved the basic codepoint display to `U+` and allowed the `U+` prefix for hex searches.
I'm keeping the hex output for the "UTF" displays as `0x` since these represent literal hex numbers as opposed to codepoints and so the `U+` prefix wouldn't make sense there.
